import { v4 as uuidv4 } from 'uuid';
export const SEARCH_KEYWORDS = [
  'ALL',
  'Order Number',
  'Item',
  'Description',
  'Vendor'
]
export const LOCAL_STORAGE_IDS = {
  user : 'fsuser',
  headersArriveTable : 'headers_arrive-table',
  viewProfile  : 'viewProfile',
  columnsHeaderProfile : 'columnsHeaderProfile',
  usedLocation : 'used-location',
  usedPerson : 'used-person',
  reference : 'reference',
  queryFilter : 'queryFilter',
  cwRangeGap : 'cwRangeGap',
  token : 'fs_token',
  expirationDate : 'expirationDate',
  userId : 'userId',
  dExists : 'd_exists'
}



export const DEFAULT_ITEM = {name:'',value:'',label:''};
export const DATE_TYPE_SELECTION = [
  { name: "Today", value: "today", label:"Today",id: "1" },
  { name: "Yesterday", value: "yesterday", label:"Yesterday", id: "2" },
  { name: "Tomorrow", value: "tomorrow", label:"Tomorrow", id: "3" },
  { name: "Last Week", value: "lastWeek", label:"Last Week", id: "4" },
  { name: "This Week", value: "thisWeek", label:"This Week", id: "5" },
  { name: "Last Month", value: "lastMonth", label:"Last Month", id: "6" },
  { name: "This Month", value: "thisMonth", label:"This Month", id: "7" },
  { name: "Next Month", value: "nextMonth", label:"Next Month", id: "8" },
  { name: "Last 30 Days", value: "last30Days", label:"Last 30 Days", id: "9" },
  { name: "Last 90 Days", value: "last90Days", label:"Last 90 Days", id: "10" },
  { name: "YTD", value: "ytd", label:"YTD", id: "11" },
  { name: "Custom", value: "custom", label:"Custom", id: "12" },
]
export const ACTION_STATUSES = {
  PENDING: 'Pending',
  SUCCEED: 'Succeed',
  FAILED: 'Failed',
  UNDEFINED: undefined
};

export const INPUT_STATUSES = {
  VALID: 'valid',
  INVALID: 'invalid',
  UNDEFINED: undefined
};

export const INPUT_CLASS_NAMES = {
  [INPUT_STATUSES.VALID]: 'valid-input',
  [INPUT_STATUSES.INVALID]: 'invalid-input'
};

export const DEFAULT_ERROR = {
  debug: 'Something went wrong',
  details: 'Something went wrong'
};


  


export const countries =  
 [
      { name: 'UNITED STATES', code: 'US' },
      { name: 'AFGHANISTAN', code: 'AF' },
      { name: 'Aland Islands', code: 'AX' },
      { name: 'ALBANIA', code: 'AL' },
      { name: 'ALGERIA', code: 'DZ' },
      { name: 'AMERICAN SAMOA', code: 'AS' },
      { name: 'ANDORRA', code: 'AD' },
      { name: 'ANGOLA', code: 'AO' },
      { name: 'ANGUILLA', code: 'AI' },
      { name: 'ANTARCTICA', code: 'AQ' },
      { name: 'ANTIGUA AND BARBUDA', code: 'AG' },
      { name: 'ARGENTINA', code: 'AR' },
      { name: 'ARMENIA', code: 'AM' },
      { name: 'ARUBA', code: 'AW' },
      { name: 'AUSTRALIA', code: 'AU' },
      { name: 'AUSTRIA', code: 'AT' },
      { name: 'AZERBAIJAN', code: 'AZ' },
      { name: 'BAHAMAS', code: 'BS' },
      { name: 'BAHRAIN', code: 'BH' },
      { name: 'BANGLADESH', code: 'BD' },
      { name: 'BARBADOS', code: 'BB' },
      { name: 'BELARUS', code: 'BY' },
      { name: 'BELGIUM', code: 'BE' },
      { name: 'BELIZE ', code: 'BZ' },
      { name: 'BENIN', code: 'BJ' },
      { name: 'BERMUDA', code: 'BM' },
      { name: 'BHUTAN', code: 'BT' },
      { name: 'BOLIVIA', code: 'BO' },
      { name: 'BOSNIA AND HERZEGOWINA', code: 'BA' },
      { name: 'BOTSWANA', code: 'BW' },
      { name: 'BOUVET ISLAND', code: 'BV' },
      { name: 'BRAZIL', code: 'BR' },
      { name: 'BRITISH INDIAN OCEAN TERRITORY', code: 'IO' },
      { name: 'BRUNEI DARUSSALAM', code: 'BN' },
      { name: 'BULGARIA', code: 'BG' },
      { name: 'BURKINA FASO', code: 'BF' },
      { name: 'BURUNDI', code: 'BI' },
      { name: 'CAMBODIA', code: 'KH' },
      { name: 'CAMEROON', code: 'CM' },
      { name: 'CANADA', code: 'CA' },
      { name: 'CAPE VERDE', code: 'CV' },
      { name: 'CAYMAN ISLANDS', code: 'KY' },
      { name: 'CENTRAL AFRICAN REPUBLIC', code: 'CF' },
      { name: 'CHAD', code: 'TD' },
      { name: 'CHILE', code: 'CL' },
      { name: 'CHINA', code: 'CN' },
      { name: 'CHRISTMAS ISLAND', code: 'CX' },
      { name: 'COCOS (KEELING) ISLANDS', code: 'CC' },
      { name: 'COLOMBIA', code: 'CO' },
      { name: 'COMOROS', code: 'KM' },
      { name: 'CONGO (Brazzaville)', code: 'CG' },
      { name: 'CONGO (Kinshasa)', code: 'CD' },
      { name: 'COOK ISLANDS', code: 'CK' },
      { name: 'COSTA RICA', code: 'CR' },
      { name: 'COTE D\'IVOIRE\'', code: 'CI' },
      { name: 'CROATIA (local name: Hrvatska)', code: 'HR' },
      { name: 'CUBA', code: 'CU' },
      { name: 'CYPRUS', code: 'CY' },
      { name: 'CZECH REPUBLIC', code: 'CZ' },
      { name: 'DENMARK', code: 'DK' },
      { name: 'DJIBOUTI', code: 'DJ' },
      { name: 'DOMINICA', code: 'DM' },
      { name: 'DOMINICAN REPUBLIC', code: 'DO' },
      { name: 'EAST TIMOR', code: 'TP' },
      { name: 'ECUADOR', code: 'EC' },
      { name: 'EGYPT', code: 'EG' },
      { name: 'EL SALVADOR', code: 'SV' },
      { name: 'EQUATORIAL GUINEA', code: 'GQ' },
      { name: 'ERITREA', code: 'ER' },
      { name: 'ESTONIA', code: 'EE' },
      { name: 'ETHIOPIA', code: 'ET' },
      { name: 'FALKLAND ISLANDS (MALVINAS)', code: 'FK' },
      { name: 'FAROE ISLANDS', code: 'FO' },
      { name: 'FIJI', code: 'FJ' },
      { name: 'FINLAND', code: 'FI' },
      { name: 'FRANCE', code: 'FR' },
      { name: 'FRANCE, METROPOLITAN', code: 'FX' },
      { name: 'FRENCH GUIANA', code: 'GF' },
      { name: 'FRENCH POLYNESIA', code: 'PF' },
      { name: 'FRENCH SOUTHERN TERRITORIES', code: 'TF' },
      { name: 'GABON', code: 'GA' },
      { name: 'GAMBIA', code: 'GM' },
      { name: 'GEORGIA', code: 'GE' },
      { name: 'GERMANY', code: 'DE' },
      { name: 'GHANA', code: 'GH' },
      { name: 'GIBRALTAR', code: 'GI' },
      { name: 'GREECE', code: 'GR' },
      { name: 'GREENLAND', code: 'GL' },
      { name: 'GRENADA', code: 'GD' },
      { name: 'GUADELOUPE', code: 'GP' },
      { name: 'GUAM', code: 'GU' },
      { name: 'GUATEMALA', code: 'GT' },
      { name: 'Guernsey, Bailiwick of', code: 'GG' },
      { name: 'GUINEA', code: 'GN' },
      { name: 'GUINEA-BISSAU', code: 'GW' },
      { name: 'GUYANA', code: 'GY' },
      { name: 'HAITI', code: 'HT' },
      { name: 'HEARD AND MC DONALD ISLANDS', code: 'HM' },
      { name: 'HOLY SEE (VATICAN CITY STATE)', code: 'VA' },
      { name: 'HONDURAS', code: 'HN' },
      { name: 'HONG KONG', code: 'HK' },
      { name: 'HUNGARY', code: 'HU' },
      { name: 'ICELAND', code: 'IS' },
      { name: 'INDIA', code: 'IN' },
      { name: 'INDONESIA', code: 'ID' },
      { name: 'IRAN (ISLAMIC REPUBLIC OF)', code: 'IR' },
      { name: 'IRAQ', code: 'IQ' },
      { name: 'IRELAND', code: 'IE' },
      { name: 'Isle of Man', code: 'IM' },
      { name: 'ISRAEL', code: 'IL' },
      { name: 'ITALY', code: 'IT' },
      { name: 'JAMAICA', code: 'JM' },
      { name: 'JAPAN', code: 'JP' },
      { name: 'Jersey, Bailiwick of', code: 'JE' },
      { name: 'JORDAN', code: 'JO' },
      { name: 'KAZAKHSTAN', code: 'KZ' },
      { name: 'KENYA', code: 'KE' },
      { name: 'KIRIBATI', code: 'KI' },
      { name: 'KOREA, D.P.R.O.', code: 'KP' },
      { name: 'KOREA, REPUBLIC OF (KR)', code: 'KR' },
      { name: 'KOREA, REPUBLIC OF (KO)', code: 'KO' },
      { name: 'KUWAIT', code: 'KW' },
      { name: 'KYRGYZSTAN', code: 'KG' },
      { name: 'LAOS', code: 'LA' },
      { name: 'LATVIA', code: 'LV' },
      { name: 'LEBANON', code: 'LB' },
      { name: 'LESOTHO', code: 'LS' },
      { name: 'LIBERIA', code: 'LR' },
      { name: 'LIBYAN ARAB JAMAHIRIYA', code: 'LY' },
      { name: 'LIECHTENSTEIN', code: 'LI' },
      { name: 'LITHUANIA', code: 'LT' },
      { name: 'LUXEMBOURG', code: 'LU' },
      { name: 'MACAU', code: 'MO' },
      { name: 'MACEDONIA', code: 'MK' },
      { name: 'MADAGASCAR', code: 'MG' },
      { name: 'MALAWI', code: 'MW' },
      { name: 'MALAYSIA', code: 'MY' },
      { name: 'MALDIVES', code: 'MV' },
      { name: 'MALI', code: 'ML' },
      { name: 'MALTA', code: 'MT' },
      { name: 'MARSHALL ISLANDS', code: 'MH' },
      { name: 'MARTINIQUE', code: 'MQ' },
      { name: 'MAURITANIA', code: 'MR' },
      { name: 'MAURITIUS', code: 'MU' },
      { name: 'MAYOTTE', code: 'YT' },
      { name: 'MEXICO', code: 'MX' },
      { name: 'MICRONESIA, FEDERATED STATES OF', code: 'FM' },
      { name: 'MOLDOVA, REPUBLIC OF', code: 'MD' },
      { name: 'MONACO', code: 'MC' },
      { name: 'MONGOLIA', code: 'MN' },
      { name: 'MONTSERRAT', code: 'MS' },
      { name: 'MOROCCO', code: 'MA' },
      { name: 'MOZAMBIQUE', code: 'MZ' },
      { name: 'MYANMAR (Burma)', code: 'MM' },
      { name: 'NAMIBIA', code: 'NA' },
      { name: 'NAURU', code: 'NR' },
      { name: 'NEPAL', code: 'NP' },
      { name: 'NETHERLANDS', code: 'NL' },
      { name: 'NETHERLANDS ANTILLES', code: 'AN' },
      { name: 'NEW CALEDONIA', code: 'NC' },
      { name: 'NEW ZEALAND', code: 'NZ' },
      { name: 'NICARAGUA', code: 'NI' },
      { name: 'NIGER', code: 'NE' },
      { name: 'NIGERIA', code: 'NG' },
      { name: 'NIUE', code: 'NU' },
      { name: 'NORFOLK ISLAND', code: 'NF' },
      { name: 'NORTHERN MARIANA ISLANDS', code: 'MP' },
      { name: 'NORWAY', code: 'NO' },
      { name: 'OMAN', code: 'OM' },
      { name: 'PAKISTAN', code: 'PK' },
      { name: 'PALAU', code: 'PW' },
      { name: 'Palestinian Territory, Occupied', code: 'PS' },
      { name: 'PANAMA', code: 'PA' },
      { name: 'PAPUA NEW GUINEA', code: 'PG' },
      { name: 'PARAGUAY', code: 'PY' },
      { name: 'PERU', code: 'PE' },
      { name: 'PHILIPPINES', code: 'PH' },
      { name: 'PITCAIRN', code: 'PN' },
      { name: 'POLAND', code: 'PL' },
      { name: 'PORTUGAL', code: 'PT' },
      { name: 'PUERTO RICO', code: 'PR' },
      { name: 'QATAR', code: 'QA' },
      { name: 'REUNION', code: 'RE' },
      { name: 'ROMANIA', code: 'RO' },
      { name: 'RUSSIAN FEDERATION', code: 'RU' },
      { name: 'RWANDA', code: 'RW' },
      { name: 'SAINT KITTS AND NEVIS', code: 'KN' },
      { name: 'SAINT LUCIA', code: 'LC' },
      { name: 'SAINT VINCENT AND THE GRENADINES', code: 'VC' },
      { name: 'SAIPAN', code: 'SS' },
      { name: 'SAMOA', code: 'WS' },
      { name: 'SAN MARINO', code: 'SM' },
      { name: 'SAO TOME AND PRINCIPE', code: 'ST' },
      { name: 'SAUDI ARABIA', code: 'SA' },
      { name: 'SENEGAL', code: 'SN' },
      { name: 'SERBIA', code: 'RS' },
      { name: 'Serbia and Montenegro', code: 'CS' },
      { name: 'SEYCHELLES', code: 'SC' },
      { name: 'SIERRA LEONE', code: 'SL' },
      { name: 'SINGAPORE', code: 'SG' },
      { name: 'SLOVAKIA (Slovak Republic)', code: 'SK' },
      { name: 'SLOVENIA', code: 'SI' },
      { name: 'SOLOMON ISLANDS', code: 'SB' },
      { name: 'SOMALIA', code: 'SO' },
      { name: 'SOUTH AFRICA', code: 'ZA' },
      { name: 'SOUTH GEORGIA AND SOUTH S.S.', code: 'GS' },
      { name: 'SPAIN', code: 'ES' },
      { name: 'SRI LANKA', code: 'LK' },
      { name: 'ST. HELENA', code: 'SH' },
      { name: 'ST. PIERRE AND MIQUELON', code: 'PM' },
      { name: 'SUDAN', code: 'SD' },
      { name: 'SURINAME', code: 'SR' },
      { name: 'SVALBARD AND JAN MAYEN ISLANDS', code: 'SJ' },
      { name: 'SWAZILAND', code: 'SZ' },
      { name: 'SWEDEN', code: 'SE' },
      { name: 'SWITZERLAND', code: 'CH' },
      { name: 'SYRIAN ARAB REPUBLIC', code: 'SY' },
      { name: 'TAIWAN', code: 'TW' },
      { name: 'TAJIKISTAN', code: 'TJ' },
      { name: 'TANZANIA, UNITED REPUBLIC OF', code: 'TZ' },
      { name: 'THAILAND', code: 'TH' },
      { name: 'Timor-Leste, Democratic Republic of', code: 'TL' },
      { name: 'TOGO', code: 'TG' },
      { name: 'TOKELAU', code: 'TK' },
      { name: 'TONGA', code: 'TO' },
      { name: 'TRINIDAD AND TOBAGO', code: 'TT' },
      { name: 'TUNISIA', code: 'TN' },
      { name: 'TURKEY', code: 'TR' },
      { name: 'TURKMENISTAN', code: 'TM' },
      { name: 'TURKS AND CAICOS ISLANDS', code: 'TC' },
      { name: 'TUVALU', code: 'TV' },
      { name: 'U.S. MINOR ISLANDS', code: 'UM' },
      { name: 'UGANDA', code: 'UG' },
      { name: 'UKRAINE', code: 'UA' },
      { name: 'UNITED ARAB EMIRATES', code: 'AE' },
      { name: 'UNITED KINGDOM', code: 'GB' },
      { name: 'URUGUAY', code: 'UY' },
      { name: 'UZBEKISTAN', code: 'UZ' },
      { name: 'VANUATU', code: 'VU' },
      { name: 'VENEZUELA', code: 'VE' },
      { name: 'VIET NAM', code: 'VN' },
      { name: 'VIRGIN ISLANDS (BRITISH)', code: 'VG' },
      { name: 'VIRGIN ISLANDS (U.S.)', code: 'VI' },
      { name: 'WALLIS AND FUTUNA ISLANDS', code: 'WF' },
      { name: 'WESTERN SAHARA', code: 'EH' },
      { name: 'YEMEN', code: 'YE' },
      { name: 'YUGOSLAVIA (Serbia and Montenegro)', code: 'YU' },
      { name: 'ZAMBIA', code: 'ZM' },
      { name: 'ZIMBABWE', code: 'ZW' }
  ]
  export const QUANTITY_UOM = [
    'Carton',
    'Box',
    'Case',
    'Pack',
    'Pcs'
    
  ]
  export const SUPPLY_VENDOR = [
    'Amazon',
    'Medline'
  ]
  export const SUPPLY_STATUS = [
    'Order',
    'Delivered',
    'Return'
  ]
  export const SUPPLY_CATEGORY = [
    'Office',
    'Underpads',
    'Brief',
    'Immnue System', 
    'Thermometer',
    'Bandages', 
    'Immnue System', 
    'Gloves',
    'Shampoo',
    'Pertoleum Jelly',
    'Food Thickener',
    'Ointment',
    'Pill Crusher and Grinder',
    'Alcohol Wipes',
    'Ointment',
    'Swabs Sponge', 
    'Urinal',
    'Carbonless Paper',
    'Blood Oxygen Monitor',
    'Saline Solution for Inhalation',
    'Perineal Cleanser', 
    'Sterile Lancets', 
    'Glycerin Swabsticks',
    'Other'
  ]

  export const SUPPLY_PAYMENT_METHOD = [
    'Cash',
    'Card',
    'Check'
  ]
  export const DIVINE_PATIENT_LIST = [
    'Nargel Velasco',
    'Jasmin Velasco'
  ]
  export const HOSPICE_FACILITIES = [
    'Pacifica',
    'Summerlin'
  ]
  export const DIVINE_EMPLOYEES = [
    {
      name: 'Jasmin Velasco',
      position: 'Office Manager'
    },
    {
      name: 'Nargel Velasco',
      position: 'Information Technology'
    },
    
  ]

  export const SAMPLE_CLIENT_DATA = [
    {name: 'John Doe',dob:'06/14/1971',gender:'M',evaluator:'Dr.Smith',admittedDt:'10/01/2022',status:'Active'},
    {name: 'John Doe 2',dob:'06/11/1971',gender:'M',evaluator:'Dr.Smith2',admittedDt:'10/01/2022',status:'Active'}
    
  ]
  export const SAMPLE_WORKER_DATA = [
    {name: 'John Doe',position:'CNA',status: 'Full-Time',hired : '09/02/2022',email:'test@2131',phone:'33'},
    {name: 'John Doe2',position:'RN',status: 'Full-Time',hired : '09/02/2022',email: 'ere2@sdsd',phone:'424'}
    
    
  ]
  export const SAMPLE_LOCATION_DATA = [
    {
      name: 'Milan TownHomes',
      address: '875 E Silverado Ranch',
      locationType: 'Residence',
      contactPerson: 'N/A',
      phone: 'N/A',
      fax : 'N/A',
      
    },
    {
      name: 'Pacifica',
      address: 'XXXX',
      locationType: 'Facilities',
      contactPerson: 'N/A',
      phone: 'N/A',
      fax : 'N/A',
      
    },
  ]
  

  export const SAMPLE_VENDOR_DATA = [
    {
      name: 'Amazon',
      website: 'amazon.com',
      location: 'N/A',
      contactPerson: 'N/A',
      phone: 'N/A',
      fax : 'N/A',
      accountNumber: 'N/A'
    },
    {
      name: 'Costco - St Rose',
      website: 'costco.com',
      location: 'St Rose ParkWay',
      contactPerson: 'N/A',
      phone: 'N/A',
      fax : 'N/A',
      accountNumber: 'N/A'
    },
    {
      name: 'Walmart - Serene',
      website: 'walmart.com',
      location: 'Serene',
      contactPerson: 'N/A',
      phone: 'N/A',
      fax : 'N/A',
      accountNumber: 'N/A'
    },
  ]
  export const SAMPLE_INVOICE_STATEMENT = [
    
      {
        invoiceDt:'9/19/22',
        invNumber:'114-3005620-2276246',
        grandTotal:'333.93',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/24/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/24/22',
        invNumber:'112-5273813-7592249',
        grandTotal:'98.72',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/27/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/12/22',
        invNumber:'114-9803757-9875403',
        grandTotal:'42.69',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/12/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/12/22',
        invNumber:'114-9699085-9844221',
        grandTotal:'59.57',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/13/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/12/22',
        invNumber:'114-1162966-3857062',
        grandTotal:'81.60',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/13/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/12/22',
        invNumber:'114-0043554-8898602',
        grandTotal:'37.65',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/13/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/6/22',
        invNumber:'114-3154953-7498667',
        grandTotal:'69.95',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/7/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/6/22',
        invNumber:'114-3061230-1910655',
        grandTotal:'144.26',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/8/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/6/22',
        invNumber:'114-2776577-0626650',
        grandTotal:'9.68',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/8/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/6/22',
        invNumber:'114-0342171-1897028',
        grandTotal:'28.14',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/7/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/6/22',
        invNumber:'114-5637127-5845036',
        grandTotal:'23.29',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/6/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/6/22',
        invNumber:'114-4722390-4361037',
        grandTotal:'133.35',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/8/22',
        vendor:'AMAZON'
    },
    {
        invoiceDt:'9/6/22',
        invNumber:'114-3190581-9967466',
        grandTotal:'23.81',
        paymentMethod:'Visa',
        paymentInfo:'Visa Ending 0485',
        paymentDt:'9/8/22',
        vendor:'AMAZON'
    }  
  ]
  export const SAMPLE_DELIVERY_RECORDS = [
    {
      recordDate : '09/22/22',
      patient : 'Joh Doe',
      facility : 'Pacifica',
      requestor : 'Jazz Velasco',
      position:'Office Manager',
      caregiver : 'Nargel Velasco',
      status : 'In process',
      details : [
        {
          id : uuidv4(),
          item : 'Test Items',
         qty: 1 ,
         qtyUom : 'Box',
         pcs : 20
        },
        {
          id : uuidv4(),
          item : 'Test Items 2',
         qty: 1 ,
         qtyUom : 'Box',
         pcs : 25
        },
        {
          id : uuidv4(),
          item : 'Test Items 3',
         qty: 1 ,
         qtyUom : 'Box',
         pcs : 30
        },
      ]
      }  
  ];
  export const SAMPLE_STOCK_ROOM_INVENTORY = [
   
    {
      item: '3-Ring Binders 1.5\'',
      description: 'Cardinal Economy 3-Ring Binders, 1.5\', Round Rings, Holds 350 Sheets, ClearVue Presentation View, Non-Stick, White, Carton of 12 (90631)',
      qtyOnHand : 1,
      expectedQty : 2,
      expectedDate : '09/27/22',
      projectedQty : 3
    },
    {
      item: '3-Ring Binders 1.5\'',
      description: 'Cardinal Economy 3-Ring Binders, 1.5\', Round Rings, Holds 350 Sheets, ClearVue Presentation View, Non-Stick, White, Carton of 12 (90631)',
      qtyOnHand : 1,
      expectedQty : 2,
      expectedDate : '09/27/22',
      projectedQty : 3
    },
  ]
  export const SAMPLE_ORDER  = [
    
    {
      orderPlaced: '9/24/22',
      orderNumber: '112-5273813-7592249 ',
      category: 'Office',
      items: '3-Ring Binders 1.5\'',
      description: 'Cardinal Economy 3-Ring Binders, 1.5\', Round Rings, Holds 350 Sheets, ClearVue Presentation View, Non-Stick, White, Carton of 12 (90631)',
      qty: '1',
      qtyUom: 'Carton',
      unitPiece: '12',
      totalUnitPiece: '12',
      vendor: 'Amazon',
      unitPrice: '32.93',
      totalPrice: '32.93',
      pricePerPcs: '2.74',
      status: 'Delivered',
      dateDelivered: '9/28/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/27/22'
  },
  {
      orderPlaced: '9/24/22',
      orderNumber: '112-5273813-7592249 ',
      category: 'Office',
      items: '3-Ring Binders 1\'',
      description: 'Cardinal Economy 3-Ring Binders, 1\', Round Rings, Holds 225 Sheets, ClearVue Presentation View, Non-Stick, White, Carton of 12 (90621)',
      qty: '1',
      qtyUom: 'Carton',
      unitPiece: '12',
      totalUnitPiece: '12',
      vendor: 'Amazon',
      unitPrice: ' $23.54 ',
      totalPrice: ' $23.54 ',
      pricePerPcs: ' $1.96 ',
      status: 'Delivered',
      dateDelivered: '9/27/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/27/22'
  },
  {
      orderPlaced: '9/24/22',
      orderNumber: '112-5273813-7592249 ',
      category: 'Office',
      items: 'Ring Binder Dividers ',
      description: 'Blue Summit Supplies 3 Ring Binder Dividers with Reinforced Edge, 1/8 Cut Tabs, Letter Size, 3 Hole Punch Section Index ',
      qty: '1',
      qtyUom: 'Box',
      unitPiece: '1',
      totalUnitPiece: '1',
      vendor: 'Amazon',
      unitPrice: ' $17.63 ',
      totalPrice: ' $17.63 ',
      pricePerPcs: ' $17.63 ',
      status: 'Delivered',
      dateDelivered: '9/27/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/27/22'
  },
  {
      orderPlaced: '9/24/22',
      orderNumber: '112-5273813-7592249 ',
      category: 'Office',
      items: '13 Gallon Trash Bags',
      description: 'FORID 13 Gallon Trash Bags - Clear Plastic Garbage Bags Medium Tall Trash Can Liners for Kitchen Office Home Waste Bins Unscented One Box with 5 Roll',
      qty: '1',
      qtyUom: 'Box',
      unitPiece: '5',
      totalUnitPiece: '5',
      vendor: 'Amazon',
      unitPrice: ' $16.99 ',
      totalPrice: ' $16.99 ',
      pricePerPcs: ' $3.40 ',
      status: 'Delivered',
      dateDelivered: '9/27/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/27/22'
  },
  {
      orderPlaced: '9/19/22',
      orderNumber: '114-3005620-2276246 ',
      category: 'Underpads',
      items: 'Heavy Absorbency 30 x 36',
      description: 'Medline Heavy Absorbency 30 x 36 Quilted Fluff and Polymer Disposable Underpads, 75 Per Case, Great for Protecting  Beds, Furniture, Surface',
      qty: '1',
      qtyUom: 'Case',
      unitPiece: '75',
      totalUnitPiece: '75',
      vendor: 'Amazon',
      unitPrice: ' $61.27 ',
      totalPrice: ' $61.27 ',
      pricePerPcs: ' $0.82 ',
      status: 'Delivered',
      dateDelivered: '9/23/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/24/22'
  },
  {
      orderPlaced: '9/19/22',
      orderNumber: '114-3005620-2276246 ',
      category: 'Brief',
      items: 'Extra Adult Briefs ',
      description: 'FitRight OptiFit Extra Adult Briefs with Tabs, Moderate Absorbency, X-Large, 57\'-66\', 4 Packs of 20 (80 total) ',
      qty: '2',
      qtyUom: 'Pack',
      unitPiece: '80',
      totalUnitPiece: '160',
      vendor: 'Amazon',
      unitPrice: ' $55.06 ',
      totalPrice: ' $110.12 ',
      pricePerPcs: ' $0.69 ',
      status: 'Delivered',
      dateDelivered: '9/23/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/24/22'
  },
  {
      orderPlaced: '9/19/22',
      orderNumber: '114-3005620-2276246 ',
      category: 'Immnue System ',
      items: 'High Protein Nutritional Shake, ',
      description: 'Ensure High Protein Nutritional Shake, 16g Protein, Meal Replacement Shakes, With Nutrients to Support Immune System $35.96 Health, Strawberry, 8 fl oz, 24 C',
      qty: '1',
      qtyUom: 'Carton',
      unitPiece: '24',
      totalUnitPiece: '24',
      vendor: 'Amazon',
      unitPrice: ' $35.96 ',
      totalPrice: ' $35.96 ',
      pricePerPcs: ' $1.50 ',
      status: 'Delivered',
      dateDelivered: '9/23/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/24/22'
  },
  {
      orderPlaced: '9/19/22',
      orderNumber: '114-3005620-2276246 ',
      category: 'Thermometer',
      items: 'Digital Thermometer ',
      description: 'MABIS Digital Thermometer for Adults, Thermometer for Adults, Children and Babies, Oral Thermometer, Rectal Thermometer, Underarm Thermometer, Tempera',
      qty: '3',
      qtyUom: 'Pcs',
      unitPiece: '1',
      totalUnitPiece: '3',
      vendor: 'Amazon',
      unitPrice: ' $2.89 ',
      totalPrice: ' $8.67 ',
      pricePerPcs: ' $2.89 ',
      status: 'Delivered',
      dateDelivered: '9/23/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/24/22'
  },
  {
      orderPlaced: '9/19/22',
      orderNumber: '114-3005620-2276246 ',
      category: 'Bandages ',
      items: 'Wound Dressing Sacrum Foam Bandages ',
      description: 'Dimora Wound Dressing Sacrum Foam Bandages Silicone Adhesive Border 7\'x7\' Waterproof Sacral Pads Absorbent Breathable Bed Sore Pressure Dressing',
      qty: '3',
      qtyUom: 'Pcs',
      unitPiece: '1',
      totalUnitPiece: '3',
      vendor: 'Amazon',
      unitPrice: ' $19.98 ',
      totalPrice: ' $59.94 ',
      pricePerPcs: ' $19.98 ',
      status: 'Delivered',
      dateDelivered: '9/23/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/24/22'
  },
  {
      orderPlaced: '9/19/22',
      orderNumber: '114-3005620-2276246 ',
      category: 'Immnue System ',
      items: 'Nutrition Shake with Fiber ',
      description: 'Ensure Original Nutrition Shake with Fiber, Small Meal Replacement Shake, Complete, Balanced Nutrition with Nutrients to Support Immune System Health, Vanilla, 8 fl oz, 24 Count',
      qty: '1',
      qtyUom: 'Carton',
      unitPiece: '24',
      totalUnitPiece: '24',
      vendor: 'Amazon',
      unitPrice: ' $38.99 ',
      totalPrice: ' $38.99 ',
      pricePerPcs: ' $1.62 ',
      status: 'Delivered',
      dateDelivered: '9/23/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/24/22'
  },
  {
      orderPlaced: '9/12/22',
      orderNumber: '114-9803757-9875403 ',
      category: 'Gloves',
      items: 'Clear Vinyl Exam Gloves  Medium',
      description: 'Basic Medical Clear Vinyl Exam Gloves - Latex-Free & Powder-Free - VGPF3002 (Case of 1,000), Medium $39.39 Sold by: Raidmax-Inc',
      qty: '1',
      qtyUom: 'Case',
      unitPiece: '1000',
      totalUnitPiece: '1000',
      vendor: 'Amazon',
      unitPrice: ' $39.39 ',
      totalPrice: ' $39.39 ',
      pricePerPcs: ' $0.04 ',
      status: 'Delivered',
      dateDelivered: '9/15/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/12/22'
  },
  {
      orderPlaced: '9/12/22',
      orderNumber: '114-9699085-9844221 ',
      category: 'Gloves',
      items: 'Clear Vinyl Exam Gloves Large',
      description: 'Schneider Clear Vinyl Exam Gloves, Latex-Free, Disposable Gloves, Medical Gloves, Cleaning Gloves, Food Prep Gloves, $54.97 Food Safe Rubber Gloves, Powder- (Case 1000) Large',
      qty: '1',
      qtyUom: 'Case',
      unitPiece: '1000',
      totalUnitPiece: '1000',
      vendor: 'Amazon',
      unitPrice: ' $54.97 ',
      totalPrice: ' $54.97 ',
      pricePerPcs: ' $0.05 ',
      status: 'Delivered',
      dateDelivered: '9/17/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/13/22'
  },
  {
      orderPlaced: '9/12/22',
      orderNumber: '114-1162966-3857062 ',
      category: 'Shampoo',
      items: 'No Rinse Shampoo',
      description: 'No Rinse Shampoo - 8 oz Bottles - Case of 24 - 00122NRN11150008 ',
      qty: '1',
      qtyUom: 'Case',
      unitPiece: '24',
      totalUnitPiece: '24',
      vendor: 'Amazon',
      unitPrice: ' $75.29 ',
      totalPrice: ' $75.29 ',
      pricePerPcs: ' $3.14 ',
      status: 'Delivered',
      dateDelivered: '9/14/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/13/22'
  },
  {
      orderPlaced: '9/12/22',
      orderNumber: '114-0043554-8898602 ',
      category: 'Pertoleum Jelly',
      items: 'Vaseline Petroleum Jelly',
      description: 'Vaseline Petroleum Jelly 7.5 Ounce Original (221ml) (6 Pack) ',
      qty: '1',
      qtyUom: 'Pack',
      unitPiece: '6',
      totalUnitPiece: '6',
      vendor: 'Amazon',
      unitPrice: ' $34.74 ',
      totalPrice: ' $34.74 ',
      pricePerPcs: ' $5.79 ',
      status: 'Delivered',
      dateDelivered: '9/15/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/13/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-3154953-7498667',
      category: 'Food Thickener',
      items: 'Instant Food Thickener',
      description: 'SimplyThick EasyMix | 200 Count of 6g Individual Packets | Gel Thickener for those with Dysphagia & Swallowing Disorders | $69.95 Creates An IDDSI Level 2 -',
      qty: '1',
      qtyUom: 'Box',
      unitPiece: '200',
      totalUnitPiece: '200',
      vendor: 'Amazon',
      unitPrice: ' $69.95 ',
      totalPrice: ' $69.95 ',
      pricePerPcs: ' $0.35 ',
      status: 'Delivered',
      dateDelivered: '9/10/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/7/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-3061230-1910655 ',
      category: 'Bandages ',
      items: 'Waterproof Wound Dressing Bandage ',
      description: 'Dimora Silicone Foam Dressing with Border Adhesive 4\'x4\' Waterproof Wound Dressing Bandage for Wound Care 10 Pack ',
      qty: '1',
      qtyUom: 'Pack',
      unitPiece: '10',
      totalUnitPiece: '10',
      vendor: 'Amazon',
      unitPrice: ' $22.99 ',
      totalPrice: ' $22.99 ',
      pricePerPcs: ' $2.30 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-3061230-1910655 ',
      category: 'Food Thickener',
      items: 'Instant Food Thickener',
      description: 'SimplyThick EasyMix | 100 Count of 12g Individual Packets | Gel Thickener for those with Dysphagia & Swallowing Disorders | Creates An IDDSI Level 3 -',
      qty: '1',
      qtyUom: 'Pack',
      unitPiece: '100',
      totalUnitPiece: '100',
      vendor: 'Amazon',
      unitPrice: ' $63.90 ',
      totalPrice: ' $63.90 ',
      pricePerPcs: ' $0.64 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-3061230-1910655 ',
      category: 'Ointment',
      items: 'Skin Protectant Ointment',
      description: 'Medpride Vitamin A & D Skin Protectant Ointment| for Body Chaffing, Diaper Rash, Cuts, Dry-Cracked Hands/Feet/Face| 5g $13.74 Packets, 144-Packets| Lanolin &',
      qty: '1',
      qtyUom: 'Pack',
      unitPiece: '144',
      totalUnitPiece: '144',
      vendor: 'Amazon',
      unitPrice: ' $13.74 ',
      totalPrice: ' $13.74 ',
      pricePerPcs: ' $0.10 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-3061230-1910655 ',
      category: 'Pill Crusher and Grinder',
      items: 'Pill Crusher and Grinder',
      description: 'HealthSmart Pill Crusher and Grinder, Crushes Vitamins and Tablets, Holds Up to 2 Pills, With Ergonomic Grips, Red ',
      qty: '5',
      qtyUom: 'Pcs',
      unitPiece: '1',
      totalUnitPiece: '5',
      vendor: 'Amazon',
      unitPrice: ' $2.82 ',
      totalPrice: ' $14.10 ',
      pricePerPcs: ' $2.82 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-2776577-0626650 ',
      category: 'Alcohol Wipes',
      items: 'Wrapped Alcohol Wipes',
      description: 'Alcohol Wipes | Individually Wrapped Alcohol Prep Pads with 70% Isopropyl Alcohol, Great for Medical & First Aid Kits | $8.93 Sterile, Antiseptic 2-Ply Alco',
      qty: '1',
      qtyUom: 'Box',
      unitPiece: '400',
      totalUnitPiece: '400',
      vendor: 'Amazon',
      unitPrice: ' $8.93 ',
      totalPrice: ' $8.93 ',
      pricePerPcs: ' $0.02 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-0342171-1897028 ',
      category: 'Ointment',
      items: 'Ointment Skin Protectant',
      description: 'Quality Choice Zinc Oxide Ointment Skin Protectant 2oz Each (Pack of 9) ',
      qty: '1',
      qtyUom: 'Pack',
      unitPiece: '9',
      totalUnitPiece: '9',
      vendor: 'Amazon',
      unitPrice: ' $25.97 ',
      totalPrice: ' $25.97 ',
      pricePerPcs: ' $2.89 ',
      status: 'Delivered',
      dateDelivered: '9/14/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/7/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-5637127-5845036 ',
      category: 'Bandages ',
      items: 'Bandage Roll',
      description: 'Covidien Kerlix Bandage Roll - 3324PK - 4.5\' x 4.1 yards, 12 Each / Pack ',
      qty: '1',
      qtyUom: 'Pack',
      unitPiece: '12',
      totalUnitPiece: '12',
      vendor: 'Amazon',
      unitPrice: ' $21.49 ',
      totalPrice: ' $21.49 ',
      pricePerPcs: ' $1.79 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/6/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-4722390-4361037 ',
      category: 'Swabs Sponge, ',
      items: 'Disposable Mouth Swabs Sponge ',
      description: '250 Count, ZIZNBA Disposable Mouth Swabs Sponge, Unflavored & Sterile Oral Swabs Dental Swabsticks for Mouth Cleaning',
      qty: '1',
      qtyUom: 'Box',
      unitPiece: '250',
      totalUnitPiece: '250',
      vendor: 'Amazon',
      unitPrice: ' $26.99 ',
      totalPrice: ' $26.99 ',
      pricePerPcs: ' $0.11 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-4722390-4361037 ',
      category: 'Urinal',
      items: 'Male Urinal with Attached Cover ',
      description: 'Dealmed Male Urinal with Attached Cover - Portable Urinals for Men with Translucent Receptacle, Shields Odors and Avoids Spills, 1 Ounce Increments Up',
      qty: '1',
      qtyUom: 'Pcs',
      unitPiece: '1',
      totalUnitPiece: '1',
      vendor: 'Amazon',
      unitPrice: ' $13.79 ',
      totalPrice: ' $13.79 ',
      pricePerPcs: ' $13.79 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-4722390-4361037 ',
      category: 'Carbonless Paper',
      items: 'Pre-Collated Giroform Hitec 2 Part Carbonless Paper ',
      description: 'Global Lab Supply 102-8511-1 Pre-Collated Giroform Hitec 2 Part Carbonless Paper, 8-1/2\' Length x 11\' Width ',
      qty: '1',
      qtyUom: 'Pcs',
      unitPiece: '1',
      totalUnitPiece: '1',
      vendor: 'Amazon',
      unitPrice: ' $20.95 ',
      totalPrice: ' $20.95 ',
      pricePerPcs: ' $20.95 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-4722390-4361037 ',
      category: 'Oximeter Blood Oxygen Saturation Monitor ',
      items: 'Fingertip Pulse Oximeter Blood Oxygen Saturation Monitor',
      description: 'Fingertip Pulse Oximeter Blood Oxygen Saturation Monitor, Heart Rate and Fast Spo2 Reading Oxygen Meter with OLED Screen AAA Batteries',
      qty: '3',
      qtyUom: 'Pcs',
      unitPiece: '1',
      totalUnitPiece: '1',
      vendor: 'Amazon',
      unitPrice: ' $9.99 ',
      totalPrice: ' $29.97 ',
      pricePerPcs: ' $9.99 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-4722390-4361037 ',
      category: 'Saline Solution for Inhalation',
      items: 'Modudose Saline Solution for Inhalation ',
      description: 'Modudose Saline Solution for Inhalation - 100/box(5257-5mL Unit Dose) ',
      qty: '1',
      qtyUom: 'Box',
      unitPiece: '100',
      totalUnitPiece: '100',
      vendor: 'Amazon',
      unitPrice: ' $16.35 ',
      totalPrice: ' $16.35 ',
      pricePerPcs: ' $0.16 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-4722390-4361037 ',
      category: 'Perineal Cleanser ',
      items: 'Premium Perineal Cleanser With AloeVera ',
      description: 'AmeriDerm Premium Perineal Cleanser With AloeVera | PH Balanced Personal Cleansing Spray | Eliminates Odors & Nourishes Perineum Skin | Convenient & H',
      qty: '1',
      qtyUom: 'Pcs',
      unitPiece: '1',
      totalUnitPiece: '1',
      vendor: 'Amazon',
      unitPrice: ' $14.99 ',
      totalPrice: ' $14.99 ',
      pricePerPcs: ' $14.99 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-3190581-9967466 ',
      category: 'Sterile Lancets ',
      items: 'TruePlus Sterile Lancets ',
      description: 'TruePlus Sterile Lancets, 28 Guage, 3 Boxes of 100 (300 Total) ',
      qty: '1',
      qtyUom: 'Box',
      unitPiece: '300',
      totalUnitPiece: '300',
      vendor: 'Amazon',
      unitPrice: ' $6.19 ',
      totalPrice: ' $6.19 ',
      pricePerPcs: ' $0.02 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  },
  {
      orderPlaced: '9/6/22',
      orderNumber: '114-3190581-9967466 ',
      category: 'Glycerin Swabsticks ',
      items: 'Lemon Glycerin Swabsticks',
      description: 'Lemon Glycerin Swabsticks Dynarex 25x3',
      qty: '2',
      qtyUom: 'Pcs',
      unitPiece: '1',
      totalUnitPiece: '1',
      vendor: 'Amazon',
      unitPrice: ' $7.89 ',
      totalPrice: ' $15.78 ',
      tpricePerPcs: ' $7.89 ',
      status: 'Delivered',
      dateDelivered: '9/9/22',
      paymentMethod: 'Card',
      paymentInfo: 'Visa ending in 0485 ',
      cardTransaction: '9/8/22'
  }
]


